runtime: python39 

instance_class: F1

env: standard

service: default

entrypoint: gunicorn -b :$PORT portfolio.wsgi:application

includes:
- secrets/secrets.yaml

handlers:
  - url: /static
    static_dir: staticfiles/
  - url: .*
    secure: always
    script: auto