# Generated by Django 3.2.3 on 2021-06-10 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_activat_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_activat_tokens',
            name='expired_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
