# Generated by Django 3.2.3 on 2021-06-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='picture',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
