# Generated by Django 3.2.3 on 2021-06-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_comments_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
