# Generated by Django 3.2.3 on 2021-06-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_comments_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='picture',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
