# Generated by Django 3.2.3 on 2021-06-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_comments_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='thead',
            new_name='thread',
        ),
    ]
