# Generated by Django 3.2.3 on 2021-06-25 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_remove_comments_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
