# Generated by Django 3.2.3 on 2021-06-29 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_comments_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='threads',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
